TITLE: The Raven's Nest
URL: https://brothertocrowsblog.netlify.app/
DESCRIPTION: Home of Brother to Crow's Blog
LANG: EN
STYLE: sans
AUTHOR: Crow
CONTACT: false
EMAIL: youremail@email.com
POST_COVER: false
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: /rss.xml
  - label: Archive
    url: /archive
